version: "3.8"
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: "delidrive_DB"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: root
    ports:
      - "3306:80"
    volumes:
      - ./data:/var/lib/mysql